name: Build and Test the project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Install pre-req packages
        run: |
          sudo apt install -y build-essential python-is-python3
      - name: Build the code
        run: |
          make
      - name: Run tests
        run: |
          python3 test.py
